### ISSUE TITLE
Minimum Rust version changed in patch release

### ISSUE THREAD

**Issue by wezm** [EmbarkStudios/spdx#21]
I'm not sure if you consider this a bug or not (people seem to have differing opinions on the interaction between changing minimum supported Rust version and semver) but I thought I'd point it out.

The 0.3.1 patch release [introduced the use of `#[non_exhaustive]`](https://github.com/EmbarkStudios/spdx/compare/0.3.0...0.3.1#diff-b4aea3e418ccdb71239b96952d9cddb6R306), which means it will now only compile on stable Rust 1.40.0.

**Comment by Jake-Shadle** [comment]
Ahh, thanks for pointing this out, I remember noticing that addition but didn't reflect that it would change the minimum Rust version. I think in this case I'm going to publish a new patch without `#[non_exhaustive]` and yank the previous version, as that enum is only an input to this lib, and I would actually prefer people to get compile errors if they are for some reason matching on it in their own crates and it changes in the future.

**Comment by wezm** [comment]
Awesome, thank you.
