### ISSUE TITLE
AGPL-3.0-or-later is not supported

### ISSUE THREAD

**Issue by fulmicoton** [EmbarkStudios/spdx#71]
AGPL-3.0-or-later seem to be unrecognized by spdx despite being part of https://spdx.org/licenses/

**Comment by Jake-Shadle** [comment]
It is. https://github.com/EmbarkStudios/spdx/blob/632a47ad8baa3d8469d0dabf2c6b9db13b9f50d0/src/identifiers.rs#L73-L77

If you are trying to parse it as a [Licensee](https://docs.rs/spdx/latest/spdx/struct.Licensee.html) that won't work, the `-or-later`/`-only` GPL suffixes are only allowed on license requirements.

**Comment by fulmicoton** [comment]
you are right! closing
